### PR TITLE
implement more intuitive zoom gesture behaviour

### LINKED ISSUE #283: Mobile zoom too sensitive?
### Describe the bug

When zooming on mobile with two fingers moving away from each other, the zoom-in action happens faster than what users are used to from other zoom implementations.

Here's a side-by-side comparison showcasing the difference
untitled

On the left side you see the image viewer of the duckduckgo.com image search, on the right side the example page of zoom-image using @zoom-image/core 0.34.0. The recordings were both done on a Sony Xperia 1 II phone running Android 12 with Firefox 125.3.0.

Note that the recordings show the finger positions used for the zoom gesture. In the left recording, the finger locations don't move relative to the underlying image point, i.e. the finger that starts on the eye of the cat remains on the eye throughout the gesture. In the zoom-image implementation, the fingers both start on a balloon each, but then both end up pointing at the sky because the balloons move out way quicker.

I think it would be more intuitive for users if zoom-image were to emulate the more common behaviour.

### Reproduction

this repo's own vanilla/svelte examples: https://stackblitz.com/github/willnguyen1312/zoom-image/tree/main/examples/with-vanilla

### Used Package Manager

npm

### Validations

- [X] Check that there isn't [already an issue](https://github.com/willnguyen1312/zoom-image/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is available

### PR DESCRIPTION
**Pull request by Pascal-So**
fixes #283

This works nicely in chrome on android, here's a comparison between the old behaviour on the left and the version of this PR on the right:

[chrome-old-new.webm](https://github.com/willnguyen1312/zoom-image/assets/18399125/b462ae57-c8a2-49d9-8401-4264c92df8e3)

Note how the two touch locations now remain pinned to the underlying image locations.

Unfortunately this doesn't work entirely yet, since the behaviour in Firefox on android is now more annoying (this is fixed in a later commit, check the [update below](https://github.com/willnguyen1312/zoom-image/pull/284#issuecomment-2102745605)):

[ff-new.webm](https://github.com/willnguyen1312/zoom-image/assets/18399125/9ecde8c5-d919-4268-b971-59c0ebc613a0)

The problem here lies with the onpointermove events. When both pointers are moving simultaneously, it can happen that firefox only sends updates for one of the pointers for a while, which means that when the other pointer finally does get an update, it arrives as a large instantaneous jump. Chrome apparently sends a more even rate of updates. Note that I've only tested this on my android phone, I don't know what the behaviour on other browsers on other operating systems would be, but I could imagine a similar problem arising for more setups than just firefox on android.

I saw that the manuelstofer/pinch-zoom library [listens to `touchmove` events](https://github.com/manuelstofer/pinchzoom/blob/dead159eb6fea063d8b7182406a4beb51383d303/src/pinch-zoom.js#L935) rather than `pointermove` events, and when testing that library the zoom appeared smooth in all browsers. I'm guessing that the update rate is more consistent for touch events.

Since I believe that the experience on firefox is now worse than it was before this PR, I'm only sending the PR as a draft to see what you think about this and to then possibly later switch to touch events depending on what comes out of our discussion.

Feel free to ask if anything is unclear!

### CODE REVIEW

**Comment by Pascal-So** [comment]
I just tried using touchmove instead of pointermove for the two-finger movements and the zoom is now just as smooth in mobile firefox as it is in mobile chrome:

[ff-and-chrome-mostly-working.webm](https://github.com/willnguyen1312/zoom-image/assets/18399125/bf38e6e4-1515-46e4-94a7-6d9a2805f936)

One remaining problem is when a finger is removed and the other continues to move the image around. There we get a sudden jump. I am tempted to completely separate the mouse and touch handling, i.e. getting rid of the pointer* events. The two-input case is only relevant for touch anyway, as you can't have two mouse inputs. For the one-input case, such edge cases might be easier to handle if the logic for the touch case is separate.

**Comment by Pascal-So** [comment]
Thank you for the nice feedback! Yeah the way that Firefox sends lower update rates on pointer events than on touch events wasn't an issue before because it was kinda hidden by the fixed delta zooming, but now with the smooth approach it does make a difference 😅

I merged the current main branch in to my branch, thanks for fixing the jumping issue when letting go of one finger!

**Comment by willnguyen1312** [comment]
Hi Pascal, I tested on my device based on [this link](https://github.com/willnguyen1312/zoom-image/pull/284#issuecomment-2094341800) deployed preview from your code. It looks awesome. I just had one minor thing to ask for. Can you add changeset to your PR by running `pnpm changeset` command and input your change as below before we merge in? Thanks :)

image

**Comment by Pascal-So** [comment]
done, is the changeset okay like this?

**Review by willnguyen1312 — APPROVED** [review]
Thanks so much for your contribution, Pascal. I learned a lot from this PR ❤️

**Comment by Pascal-So** [comment]
thanks for merging!

also, i just found a small detail that I want to improve about the double tap zoom behaviour, so don't spend too much effort on releasing everything yet 😅. PR incoming in a few minutes 😁

**Comment by willnguyen1312** [comment]
No worries. It's automatically executed by Github action. It's just a matter of few clicks from my side. The reason I asked for changset because it will collect you as contributor in [Changelog](https://github.com/willnguyen1312/zoom-image/blob/main/packages/core/CHANGELOG.md#0342) 😊

**Comment by Pascal-So** [comment]
okay it's not gonna be today, looks a bit more tricky than I expected :D

**Comment by willnguyen1312** [comment]
Take your time buddy 😊 I noticed it's rather late in Zurich. Thanks for your meaningful collaboration, good night and catch you later 😊

**Pull request merged**
